import './globals.css';
import {
  Josefin_Sans,
  Source_Serif_Pro,
  Open_Sans,
  Hahmlet,
} from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SideBar from '@/components/SideBar';
import Inner from '@/components/Inner';
import ContactMe from '@/components/ContactMe';
import Nav from '@/components/Nav';

const sourceSerifPro = Source_Serif_Pro({
  weight: ['200', '300', '400', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-source-serif-pro',
});
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin',
});
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});
const hahmlet = Hahmlet({
  subsets: ['latin'],
  variable: '--font-hahmlet',
});

export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
};

const fontVariables = [
  josefinSans.variable,
  openSans.variable,
  sourceSerifPro.variable,
  hahmlet.variable,
].join(' ');

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko' className={fontVariables}>
      <body className='flex flex-col mx-auto bg-uBgColor min-h-screen'>
        <Nav />
        <Inner>
          <Header />
          <main className='flex gap-20 w-full'>
            <section className='w-2/3'>{children}</section>
            <SideBar />
          </main>
        </Inner>
        <ContactMe />
        <Footer />
      </body>
    </html>
  );
}
